### ISSUE TITLE
Your theme's demo is not working on the Hugo Themes website

### ISSUE THREAD

**Issue by digitalcraftsman** [lambdafu/hugo-finite#3]
Hello @lambdafu,

you might (not) have noticed that the demo of your theme at https://themes.gohugo.io/ has been disabled a while ago. The demo itself builds fine. However, your theme takes up about 77MB of disk space, which doesn't make it ideal for distribution.

The maintainers of the Hugo theme repository (I'm one of them) started a "spring cleaning", meaning that we start to sort out themes whose build break or are otherwise blacklisted (meaning no demo is generated).

Your theme has been suggested to be removed (follow discussion at https://github.com/gohugoio/hugoThemes/pull/465). Hence, I would like ask you if it is possible to minimize the size of theme to a necessary minimum.

**Comment by lambdafu** [comment]
The size is due to included MathJax. It's common to use a CDN, but that's not ideal from a privacy point of view, and makes compliance with EU GDPR more complicated. I am considering using [KaTex](https://github.com/KaTeX/KaTeX) as a light-weight alternative. It should be good enough for most purposes. Thanks for the heads up!

**Comment by lambdafu** [comment]
MathJax is replaced by KaTex, so the working tree is now much smaller.

**Comment by lambdafu** [comment]
So, here some random notes that may or may not influence your decision to include this theme:
* I'm not primarily a theme designer/developer, but merely publish themes I am creating for my own use. BTW, great job preserving compatibility across hugo major versions!
* I am happy to include fixes and improvements, but I am not tracking new upstream features, best practices for theme design, etc, unless I have a need.
* I have another theme at https://github.com/neopg-org/neopg-theme (in production at https://neopg.io) which I developed in the last year, and that I didn't even publish to gohugo (although I'd be happy to do so). Experience from that will eventually be merged back into hugo-finite.
* There are not so many academic themes on gohugo, so this might fill a niche. It's based on two other similar researcher blogs that use hugo (but those didn't publish their versions, so I wanted to give back).
* I am currently in the process adding remarkjs based presentations to hugo-finite!

**Comment by onedrawingperday** [comment]
Hi @lambdafu 

I am the other maintainer of Hugo Themes, the one who opened that PR to remove your theme! 😉

- Your theme's size was brought down significantly by changing to KaTex.
- The theme's size on disk is now: 37.2 MB down from 77 MB.
 - The new size is comparable to the size of other Hugo Themes that are currently listed on the Hugo website.
- Your theme's demo builds fine when I test it locally.

So I have closed the PR to have your theme removed and opened another one to have your theme whitelisted in the Themes Site Build Script so that its demo is once again published on the website.

BTW the other theme that you use at https://neopg.io looks very cool. 👍 

We always welcome new theme submissions, so if you feel like having this theme included on the Hugo website, then please open an issue at https://github.com/gohugoio/hugoThemes/issues/ and also have a look at the updated [README](https://github.com/gohugoio/hugoThemes/#hugo-themes)

Also a big thanks @digitalcraftsman for opening this issue and to you for responding in a timely fashion!

**Comment by digitalcraftsman** [comment]
Moin Marcus,

thank you for responding so quickly. I've merged @onedrawingperday's PR to whitelist your theme again.

**Comment by digitalcraftsman** [comment]
For the record: this issue is fixed and the issue can be closed.
